FROM ruby:3.2

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        libcurl4-openssl-dev \
        git \
        nodejs \
        npm \
        shared-mime-info \
        libsqlite3-dev \
        tzdata \
        libyaml-dev \
        yarnpkg \
        zlib1g-dev &&\
    apt-get clean

RUN mkdir /app /gem
WORKDIR /app

RUN gem update --system && \
    gem install rails -v 7.1.1 && |
    rails new .

COPY . /gem
RUN bundle add meta_request --path /gem
RUN bundle install

COPY res/routes.rb /app/config/
COPY res/dummy_controller.rb /app/app/controllers/
COPY res/dummy /app/app/views/dummy
COPY res/meta_request_test.rb /app/test/integration/

RUN bundle exec rails db:migrate

ENV PARALLEL_WORKERS 1

CMD ["bin/rake"]
