FROM ruby:2.6-alpine

RUN apk add --update --no-cache \
        build-base \
        curl-dev \
        git \
        nodejs \
        sqlite-dev \
        tzdata \
        yaml-dev \
        yarn \
        zlib-dev

RUN mkdir /app /gem
WORKDIR /app

RUN gem update --system
RUN gem install rails -v 5.0.7.2
RUN rails new .

RUN bundle remove sqlite3
RUN bundle add sqlite3 --version '~> 1.3.6'
COPY . /gem
RUN bundle add meta_request --path /gem
RUN bundle install

COPY res/routes.rb /app/config/
COPY res/dummy_controller.rb /app/app/controllers/
COPY res/dummy /app/app/views/dummy
COPY res/meta_request_test.rb /app/test/integration/

CMD ["bin/rake"]
