require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.name = 'test'
  t.libs << 'test/unit'
  t.test_files = FileList['test/unit/**/*_test.rb']
end

task :default => :test
